[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "py-zammad-cti"
dynamic = ["version", "description", "authors", "keywords"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests==2.32.4",
    "classmods==1.2.1"
]
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}


[tool.setuptools.dynamic]
version = {attr = "zammad_cti.__version__"}
description = {attr = "zammad_cti.__description__"}
authors = {attr = "zammad_cti.__authors__"}
keywords = {attr = "zammad_cti.__keywords__"}


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]
include = ["zammad_cti*", "zammad_cti.*"]
exclude = ["test*", "dev*", "scripts*"]


[tool.setuptools.package-data]
zammad_cti = [
    "README.md",
    "LICENSE",
]


[tool.setuptools.exclude-package-data]
zammad_cti = [
    "__pycache__/*",
    "*.pyc",
    "*.so"
]


[project.urls]
Homepage = "https://github.com/devixa-tech/py-zammad-cti"
BugTracker = "https://github.com/devixa-tech/py-zammad-cti/issues"
